apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: hors-prod-cluster-01-control-plane
  namespace: hors-prod
spec:
  replicas: 1
  version: v1.33.2
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackMachineTemplate
      name: hors-prod-cluster-01-control-plane
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        name: '{{ local_hostname }}'
        kubeletExtraArgs:
          cloud-provider: external
          #provider-id: "openstack:///'{{ instance_id }}'"
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    joinConfiguration:
      nodeRegistration:
        name: '{{ local_hostname }}'
        kubeletExtraArgs:
          cloud-provider: external
          #provider-id: "openstack:///'{{ instance_id }}'"
    preKubeadmCommands:
      - apt-get update
      - apt-get install -y socat conntrack ebtables