apiVersion: v1
kind: Namespace
metadata:
  name: capo-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: openstack
  namespace: capi-operator-system
spec:
  version: v0.11.0
  configSecret:
    name: capo-variables
    namespace: capo-system
---
apiVersion: v1
kind: Secret
metadata:
  name: capo-variables
  namespace: capo-system
type: Opaque
stringData:
  OPENSTACK_CLOUD: "openstack"
  OPENSTACK_CLOUD_CACERT_B64: ""
  OPENSTACK_CLOUD_PROVIDER_CONF_B64: ""
  OPENSTACK_DNS_NAMESERVERS: "8.8.8.8"

