apiVersion: v1
kind: Namespace
metadata:
  name: capi-operator-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: capi-operator
  namespace: capi-operator-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/cluster-api-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capi-operator
  namespace: capi-operator-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cluster-api-operator
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: capi-operator
        namespace: capi-operator-system
      interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 3
  values:
    manager:
      featureGates:
        core:
          ClusterTopology: true
        kubeadmBootstrap:
          ClusterTopology: true